use axum::{
    extract::{Path, State},
    http::StatusCode,
    response::IntoResponse,
    Extension, Json,
};
use chrono::{Duration, Utc};
use uuid::Uuid;

use crate::error::AppError;
use crate::models::staff::{
    AddStaffRequest, EventStaff, ScanRequest, ScanResponse, ScannerInfoResponse,
};
use crate::utils::jwt::Claims;
use crate::utils::qr;
use crate::{utils, AppState};

// ─── helpers ────────────────────────────────────────────────────────────────

/// Fetch event and verify it exists (404) and that `organizer_id == claims.sub` (403).
async fn verify_event_ownership(
    state: &AppState,
    event_id: Uuid,
    organizer_id: Uuid,
) -> Result<crate::models::event::Event, AppError> {
    let event = sqlx::query_as::<_, crate::models::event::Event>(
        "SELECT * FROM events WHERE id = $1",
    )
    .bind(event_id)
    .fetch_optional(&state.db)
    .await?
    .ok_or_else(|| AppError::NotFound("Event not found".to_string()))?;

    if event.organizer_id != organizer_id {
        return Err(AppError::Forbidden("Forbidden".to_string()));
    }

    Ok(event)
}

// ─── 4.1  GET /api/organizer/events/:eventId/staff ──────────────────────────

pub async fn list_staff(
    State(state): State<AppState>,
    Extension(claims): Extension<Claims>,
    Path(event_id): Path<Uuid>,
) -> Result<impl IntoResponse, AppError> {
    verify_event_ownership(&state, event_id, claims.sub).await?;

    let staff = sqlx::query_as::<_, EventStaff>(
        "SELECT * FROM event_staff WHERE event_id = $1 ORDER BY created_at ASC",
    )
    .bind(event_id)
    .fetch_all(&state.db)
    .await?;

    Ok(Json(staff))
}

// ─── 4.2  POST /api/organizer/events/:eventId/staff ─────────────────────────

pub async fn add_staff(
    State(state): State<AppState>,
    Extension(claims): Extension<Claims>,
    Path(event_id): Path<Uuid>,
    Json(body): Json<AddStaffRequest>,
) -> Result<impl IntoResponse, AppError> {
    let event = verify_event_ownership(&state, event_id, claims.sub).await?;

    // Validate required fields
    if body.name.trim().is_empty() || body.email.trim().is_empty() || body.phone_number.trim().is_empty() {
        return Err(AppError::BadRequest(
            "name, email, and phone_number are required".to_string(),
        ));
    }

    // Insert new staff member (access_token generated by DB default)
    let staff = sqlx::query_as::<_, EventStaff>(
        r#"INSERT INTO event_staff (event_id, organizer_id, name, email, phone_number)
           VALUES ($1, $2, $3, $4, $5)
           RETURNING *"#,
    )
    .bind(event_id)
    .bind(claims.sub)
    .bind(body.name.trim())
    .bind(body.email.trim())
    .bind(body.phone_number.trim())
    .fetch_one(&state.db)
    .await
    .map_err(|e| {
        let msg = e.to_string();
        if msg.contains("event_staff_unique_email") {
            AppError::Conflict(
                "Staff with this email already exists for this event".to_string(),
            )
        } else {
            AppError::Database(e)
        }
    })?;

    // Fetch organizer's full_name for the email
    let organizer_name: String = sqlx::query_scalar(
        "SELECT full_name FROM users WHERE id = $1",
    )
    .bind(claims.sub)
    .fetch_optional(&state.db)
    .await?
    .unwrap_or_else(|| "Organizer".to_string());

    // Build scanner link — format: /scan/{event-slug}/{access_token}
    let slug: String = event.title
        .to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-");
    let scanner_link = format!(
        "{}/scan/{}/{}",
        state.config.app_base_url, slug, staff.access_token
    );

    // Send invite email (fire-and-forget)
    if state.config.smtp_username.is_empty() || state.config.smtp_password.is_empty() {
        tracing::info!(
            "📧 [DEV] Scanner invite for {} ({}): {}",
            staff.name, staff.email, scanner_link
        );
    } else {
        let email_result = utils::email::send_scanner_invite(
            &staff.email,
            &staff.name,
            &organizer_name,
            &event.title,
            event.event_date,
            &scanner_link,
            &state.config,
        )
        .await;

        match email_result {
            Ok(_) => tracing::info!("📧 Scanner invite sent to {}", staff.email),
            Err(e) => tracing::error!(
                "Failed to send scanner invite email to {}: {}\n📧 [DEV] Scanner link: {}",
                staff.email, e, scanner_link
            ),
        }
    }

    Ok((StatusCode::CREATED, Json(staff)).into_response())
}

// ─── 4.3  DELETE / PATCH revoke / PATCH restore ─────────────────────────────

pub async fn delete_staff(
    State(state): State<AppState>,
    Extension(claims): Extension<Claims>,
    Path((event_id, staff_id)): Path<(Uuid, Uuid)>,
) -> Result<impl IntoResponse, AppError> {
    verify_event_ownership(&state, event_id, claims.sub).await?;

    let result = sqlx::query(
        "DELETE FROM event_staff WHERE id = $1 AND event_id = $2",
    )
    .bind(staff_id)
    .bind(event_id)
    .execute(&state.db)
    .await?;

    if result.rows_affected() == 0 {
        return Err(AppError::NotFound("Staff member not found".to_string()));
    }

    Ok(StatusCode::NO_CONTENT.into_response())
}

pub async fn revoke_staff(
    State(state): State<AppState>,
    Extension(claims): Extension<Claims>,
    Path((event_id, staff_id)): Path<(Uuid, Uuid)>,
) -> Result<impl IntoResponse, AppError> {
    verify_event_ownership(&state, event_id, claims.sub).await?;

    let staff = sqlx::query_as::<_, EventStaff>(
        r#"UPDATE event_staff
           SET is_revoked = TRUE, updated_at = NOW()
           WHERE id = $1 AND event_id = $2
           RETURNING *"#,
    )
    .bind(staff_id)
    .bind(event_id)
    .fetch_optional(&state.db)
    .await?
    .ok_or_else(|| AppError::NotFound("Staff member not found".to_string()))?;

    Ok(Json(staff))
}

pub async fn restore_staff(
    State(state): State<AppState>,
    Extension(claims): Extension<Claims>,
    Path((event_id, staff_id)): Path<(Uuid, Uuid)>,
) -> Result<impl IntoResponse, AppError> {
    verify_event_ownership(&state, event_id, claims.sub).await?;

    let staff = sqlx::query_as::<_, EventStaff>(
        r#"UPDATE event_staff
           SET is_revoked = FALSE, updated_at = NOW()
           WHERE id = $1 AND event_id = $2
           RETURNING *"#,
    )
    .bind(staff_id)
    .bind(event_id)
    .fetch_optional(&state.db)
    .await?
    .ok_or_else(|| AppError::NotFound("Staff member not found".to_string()))?;

    Ok(Json(staff))
}

// ─── Helper: check scanner time window ──────────────────────────────────────

#[derive(sqlx::FromRow)]
struct EventTimings {
    gate_open_time: Option<chrono::DateTime<Utc>>,
    event_end_time: Option<chrono::DateTime<Utc>>,
}

fn check_scanner_time_window(timings: &EventTimings, event_date: chrono::DateTime<Utc>) -> Result<(), AppError> {
    let now = Utc::now();

    // Check if event has ended
    if let Some(end_time) = timings.event_end_time {
        if now > end_time {
            return Err(AppError::Gone(
                "This scanner has expired because the event has ended.".to_string(),
            ));
        }
    }

    // Check if scanner window has opened (30 min before gate_open_time or event_date)
    let reference_time = timings.gate_open_time.unwrap_or(event_date);
    let access_start = reference_time - Duration::minutes(30);

    if now < access_start {
        return Err(AppError::Locked(
            "Scanner will be available 30 minutes before gate open time.".to_string(),
        ));
    }

    Ok(())
}

// ─── 4.4  GET /api/organizer/events/:eventId/staff/scanner/:accessToken ──────

pub async fn scanner_info(
    State(state): State<AppState>,
    Path((event_id, access_token)): Path<(Uuid, Uuid)>,
) -> Result<impl IntoResponse, AppError> {
    // Look up staff by (access_token, event_id)
    let staff = sqlx::query_as::<_, EventStaff>(
        "SELECT * FROM event_staff WHERE access_token = $1 AND event_id = $2",
    )
    .bind(access_token)
    .bind(event_id)
    .fetch_optional(&state.db)
    .await?
    .ok_or_else(|| AppError::NotFound("Scanner not found".to_string()))?;

    if staff.is_revoked {
        return Err(AppError::Forbidden("Access revoked".to_string()));
    }
    if !staff.is_active {
        return Err(AppError::Forbidden("Access inactive".to_string()));
    }

    // Fetch event details
    let (event_name, event_date, gate_open_time, event_end_time): (String, chrono::DateTime<Utc>, Option<chrono::DateTime<Utc>>, Option<chrono::DateTime<Utc>>) =
        sqlx::query_as("SELECT title, event_date, gate_open_time, event_end_time FROM events WHERE id = $1")
            .bind(event_id)
            .fetch_one(&state.db)
            .await?;

    // Enforce time window
    check_scanner_time_window(&EventTimings { gate_open_time, event_end_time }, event_date)?;

    // Count daily scans for this staff member
    let daily_scan_count: i64 = sqlx::query_scalar(
        r#"SELECT COUNT(*) FROM scanned_tickets
           WHERE staff_id = $1 AND DATE(scanned_at) = CURRENT_DATE"#,
    )
    .bind(staff.id)
    .fetch_one(&state.db)
    .await?;

    Ok(Json(ScannerInfoResponse {
        event_id,
        event_name,
        event_date,
        gate_open_time,
        event_end_time,
        daily_scan_count,
        staff_name: staff.name,
    }))
}

// ─── 4.5  POST /api/organizer/events/:eventId/staff/scanner/:accessToken/scan ─

pub async fn scanner_scan(
    State(state): State<AppState>,
    Path((event_id, access_token)): Path<(Uuid, Uuid)>,
    Json(body): Json<ScanRequest>,
) -> Result<impl IntoResponse, AppError> {
    // Look up staff by (access_token, event_id)
    let staff = sqlx::query_as::<_, EventStaff>(
        "SELECT * FROM event_staff WHERE access_token = $1 AND event_id = $2",
    )
    .bind(access_token)
    .bind(event_id)
    .fetch_optional(&state.db)
    .await?
    .ok_or_else(|| AppError::NotFound("Scanner not found".to_string()))?;

    // Check revocation first
    if staff.is_revoked {
        return Err(AppError::Forbidden("Access revoked".to_string()));
    }

    // Enforce time window on scan endpoint too
    let (event_date, gate_open_time, event_end_time): (chrono::DateTime<Utc>, Option<chrono::DateTime<Utc>>, Option<chrono::DateTime<Utc>>) =
        sqlx::query_as("SELECT event_date, gate_open_time, event_end_time FROM events WHERE id = $1")
            .bind(event_id)
            .fetch_one(&state.db)
            .await?;

    check_scanner_time_window(&EventTimings { gate_open_time, event_end_time }, event_date)?;

    // Verify QR HMAC
    let qr_result = qr::verify_qr_payload(&body.qr_data, &state.config.jwt_secret);
    let (ticket_id, qr_event_id, user_id) = match qr_result {
        None => {
            return Ok(Json(ScanResponse {
                status: "INVALID_TICKET".to_string(),
                message: "Invalid or forged ticket".to_string(),
                attendee_name: None,
            })
            .into_response());
        }
        Some(ids) => ids,
    };

    // Verify ticket belongs to this event
    if qr_event_id != event_id {
        return Ok(Json(ScanResponse {
            status: "INVALID_TICKET".to_string(),
            message: "Invalid or forged ticket".to_string(),
            attendee_name: None,
        })
        .into_response());
    }

    // Begin transaction
    let mut tx = state.db.begin().await?;

    // SELECT ticket FOR UPDATE and fetch current owner info
    let ticket_info: Option<(Uuid, Uuid, Option<Uuid>, Option<String>)> = sqlx::query_as(
        "SELECT id, user_id, original_user_id, transferred_to_name FROM tickets WHERE id = $1 FOR UPDATE",
    )
    .bind(ticket_id)
    .fetch_optional(&mut *tx)
    .await?;

    let (ticket_db_id, current_user_id, original_user_id, transferred_name) = match ticket_info {
        Some(row) => row,
        None => {
            tx.rollback().await.ok();
            return Ok(Json(ScanResponse {
                status: "INVALID_TICKET".to_string(),
                message: "Invalid or forged ticket".to_string(),
                attendee_name: None,
            })
            .into_response());
        }
    };

    // Check if already scanned
    let already_scanned: Option<Uuid> = sqlx::query_scalar(
        "SELECT id FROM scanned_tickets WHERE ticket_id = $1",
    )
    .bind(ticket_id)
    .fetch_optional(&mut *tx)
    .await?;

    if already_scanned.is_some() {
        tx.rollback().await.ok();
        return Ok(Json(ScanResponse {
            status: "TICKET_ALREADY_SCANNED".to_string(),
            message: "Ticket already scanned".to_string(),
            attendee_name: None,
        })
        .into_response());
    }

    // Mark ticket as used
    sqlx::query(
        "UPDATE tickets SET status = 'used', scanned_at = NOW() WHERE id = $1",
    )
    .bind(ticket_id)
    .execute(&mut *tx)
    .await?;

    // Insert into scanned_tickets
    sqlx::query(
        "INSERT INTO scanned_tickets (staff_id, ticket_id, event_id) VALUES ($1, $2, $3)",
    )
    .bind(staff.id)
    .bind(ticket_id)
    .bind(event_id)
    .execute(&mut *tx)
    .await?;

    // Update staff counters
    sqlx::query(
        r#"UPDATE event_staff
           SET tickets_scanned = tickets_scanned + 1,
               last_active_at = NOW(),
               updated_at = NOW()
           WHERE id = $1"#,
    )
    .bind(staff.id)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    let mut attendee_name: Option<String> = None;

    if Some(current_user_id) == original_user_id && transferred_name.is_some() {
        // Pending transfer to unregistered recipient uses transferred name
        attendee_name = transferred_name;
    } else {
        // Normal purchase or registered recipient uses their profile name
        attendee_name = sqlx::query_scalar(
            "SELECT full_name FROM users WHERE id = $1",
        )
        .bind(current_user_id)
        .fetch_optional(&state.db)
        .await?;
    }

    Ok(Json(ScanResponse {
        status: "VALID_TICKET".to_string(),
        message: "Entry granted".to_string(),
        attendee_name,
    })
    .into_response())
}

// ─── Public: GET /api/scanner/:accessToken ───────────────────────────────────

pub async fn public_scanner_info(
    State(state): State<AppState>,
    Path(access_token): Path<Uuid>,
) -> Result<impl IntoResponse, AppError> {
    let staff = sqlx::query_as::<_, EventStaff>(
        "SELECT * FROM event_staff WHERE access_token = $1",
    )
    .bind(access_token)
    .fetch_optional(&state.db)
    .await?
    .ok_or_else(|| AppError::NotFound("Scanner not found".to_string()))?;

    if staff.is_revoked {
        return Err(AppError::Forbidden("Access revoked".to_string()));
    }
    if !staff.is_active {
        return Err(AppError::Forbidden("Access inactive".to_string()));
    }

    let event_id = staff.event_id;

    let (event_name, event_date, gate_open_time, event_end_time): (String, chrono::DateTime<Utc>, Option<chrono::DateTime<Utc>>, Option<chrono::DateTime<Utc>>) =
        sqlx::query_as("SELECT title, event_date, gate_open_time, event_end_time FROM events WHERE id = $1")
            .bind(event_id)
            .fetch_one(&state.db)
            .await?;

    // Enforce time window
    check_scanner_time_window(&EventTimings { gate_open_time, event_end_time }, event_date)?;

    let daily_scan_count: i64 = sqlx::query_scalar(
        r#"SELECT COUNT(*) FROM scanned_tickets
           WHERE staff_id = $1 AND DATE(scanned_at) = CURRENT_DATE"#,
    )
    .bind(staff.id)
    .fetch_one(&state.db)
    .await?;

    Ok(Json(ScannerInfoResponse {
        event_id,
        event_name,
        event_date,
        gate_open_time,
        event_end_time,
        daily_scan_count,
        staff_name: staff.name,
    }))
}

// ─── 4.6  GET /api/organizer/events/:eventId/staff/:staffId/scans ────────────

pub async fn list_scanned_attendees(
    State(state): State<AppState>,
    Extension(claims): Extension<Claims>,
    Path((event_id, staff_id)): Path<(Uuid, Uuid)>,
) -> Result<impl IntoResponse, AppError> {
    verify_event_ownership(&state, event_id, claims.sub).await?;

    let staff_name = sqlx::query_scalar::<_, String>(
        "SELECT name FROM event_staff WHERE id = $1 AND event_id = $2"
    )
    .bind(staff_id)
    .bind(event_id)
    .fetch_optional(&state.db)
    .await?
    .unwrap_or_else(|| "Unknown Staff".to_string());

    let attendees = sqlx::query_as::<_, crate::models::staff::ScannedAttendee>(
        r#"
        SELECT 
            st.ticket_id,
            COALESCE(
                CASE WHEN t.original_user_id = t.user_id THEN t.transferred_to_name ELSE NULL END, 
                u.full_name
            ) as attendee_name,
            COALESCE(
                CASE WHEN t.original_user_id = t.user_id THEN t.transferred_to_email ELSE NULL END, 
                u.email
            ) as attendee_email,
            t.ticket_type,
            st.scanned_at
        FROM scanned_tickets st
        JOIN tickets t ON st.ticket_id = t.id
        JOIN users u ON t.user_id = u.id
        WHERE st.staff_id = $1 AND st.event_id = $2
        ORDER BY st.scanned_at DESC
        "#,
    )
    .bind(staff_id)
    .bind(event_id)
    .fetch_all(&state.db)
    .await?;

    Ok(Json(crate::models::staff::ScannedAttendeesResponse {
        staff_name,
        attendees,
    }).into_response())
}
